-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.dealer
(
    id bigserial NOT NULL,
    name character varying(255) NOT NULL,
    percent numeric NOT NULL,
    comment text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.currency
(
    id bigserial NOT NULL,
    name character varying(255) NOT NULL,
    short_name character varying(64),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.course
(
    cur_id_from bigint NOT NULL,
    cur_id_to bigint NOT NULL,
    date_from timestamp without time zone NOT NULL,
    date_to timestamp without time zone NOT NULL,
    value numeric NOT NULL,
    PRIMARY KEY (cur_id_from, cur_id_to, date_from)
);

CREATE TABLE IF NOT EXISTS public.product_group
(
    id bigserial NOT NULL,
    name character varying(255) NOT NULL,
    comment text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product
(
    id bigserial NOT NULL,
    group_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bank
(
    id bigserial NOT NULL,
    name character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.managers
(
    id bigserial NOT NULL,
    dealer_id bigint,
    first_name character varying(255) NOT NULL,
    second_name character varying(255) NOT NULL,
    hire_date timestamp without time zone NOT NULL,
    comment text,
    parent_id bigint,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tax
(
    id bigserial NOT NULL,
    name character varying(255) NOT NULL,
    value integer NOT NULL,
    comment text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.contractor
(
    id bigserial NOT NULL,
    name character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    comment text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.outgoing
(
    id bigserial NOT NULL,
    prod_id bigint NOT NULL,
    tax_id bigint,
    contractor_id bigint,
    manager_id bigint NOT NULL,
    date timestamp without time zone NOT NULL,
    qty integer NOT NULL,
    cost numeric NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.incoming
(
    id bigserial NOT NULL,
    product_id bigint NOT NULL,
    tax bigint,
    contractor_id bigint,
    manager_id bigint NOT NULL,
    date timestamp without time zone NOT NULL,
    qty integer NOT NULL,
    cost numeric NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_price
(
    product_id bigint NOT NULL,
    date_from timestamp without time zone NOT NULL,
    cur_id bigint NOT NULL,
    date_to timestamp without time zone NOT NULL,
    value numeric NOT NULL,
    PRIMARY KEY (product_id, date_from)
);

CREATE TABLE IF NOT EXISTS public.account
(
    id bigserial NOT NULL,
    bank_id bigint NOT NULL,
    contractor_id bigint NOT NULL,
    "number" integer NOT NULL,
    date_from timestamp without time zone NOT NULL,
    date_to timestamp without time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.contract
(
    contractor_id bigint NOT NULL,
    manager_id bigint NOT NULL,
    date_from timestamp without time zone NOT NULL,
    date_to timestamp without time zone NOT NULL,
    PRIMARY KEY (contractor_id, manager_id)
);

ALTER TABLE IF EXISTS public.course
    ADD FOREIGN KEY (cur_id_from)
    REFERENCES public.currency (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.course
    ADD FOREIGN KEY (cur_id_to)
    REFERENCES public.currency (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT prod_group FOREIGN KEY (group_id)
    REFERENCES public.product_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.managers
    ADD CONSTRAINT dealer FOREIGN KEY (dealer_id)
    REFERENCES public.dealer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.managers
    ADD CONSTRAINT parent_manager FOREIGN KEY (parent_id)
    REFERENCES public.managers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.outgoing
    ADD CONSTRAINT productt FOREIGN KEY (prod_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.outgoing
    ADD CONSTRAINT tax_id FOREIGN KEY (tax_id)
    REFERENCES public.tax (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.outgoing
    ADD CONSTRAINT cont FOREIGN KEY (contractor_id)
    REFERENCES public.contractor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.outgoing
    ADD CONSTRAINT man FOREIGN KEY (manager_id)
    REFERENCES public.managers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.incoming
    ADD CONSTRAINT prod_id FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.incoming
    ADD CONSTRAINT taxx FOREIGN KEY (tax)
    REFERENCES public.tax (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.incoming
    ADD CONSTRAINT contr_idd FOREIGN KEY (contractor_id)
    REFERENCES public.contractor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.incoming
    ADD CONSTRAINT man_id FOREIGN KEY (manager_id)
    REFERENCES public.managers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.product_price
    ADD CONSTRAINT prod FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.product_price
    ADD CONSTRAINT cur FOREIGN KEY (cur_id)
    REFERENCES public.currency (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.account
    ADD CONSTRAINT bankk FOREIGN KEY (bank_id)
    REFERENCES public.bank (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.account
    ADD CONSTRAINT contactorrrr FOREIGN KEY (contractor_id)
    REFERENCES public.contractor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.contract
    ADD CONSTRAINT contracotrrrr FOREIGN KEY (contractor_id)
    REFERENCES public.contractor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.contract
    ADD CONSTRAINT managgeer FOREIGN KEY (manager_id)
    REFERENCES public.managers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
